#!/usr/bin/python3
# ©　2023 Masanao Hayashi
# SPDX-License-Identifier: BSD-3-Claus
import sys

def tonum(s):
    try:
        return int(s)
    except:
        return float(s)

ans = 0
for line in sys.stdin:
    line = line.rstrip()
    ans += tonum(line)

print(ans)

